spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: ture
        show_sql: true
    defer-datasource-initialization: true


  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console