spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: ture
        dialect: org.hibernate.dialect.PostgreSQLDialect


  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console