### GET request with a header
GET http://localhost:8080
Accept: application/json

### Send POST request with json body
POST http://localhost:8080/csrf
Content-Type: application/json

### Send POST request with json body
POST http://localhost:8080/csrf
Content-Type: application/x-www-form-urlencoded

_csrf = Tf6U8OJ6hWBR_CWAA7Fc51tpfGGwtomFlgeAscowwlokY4MAKZryk4NL51F8yxzlMpxo1z0NUQOHg-iooDS5hvlS-jlHVeIz

### Send POST request with json body
POST http://localhost:8080/ignoreCsrf
Content-Type: application/json

### GET request with a header
GET http://localhost:8080/csrfToken
Accept: application/json